import type { Metadata } from "next";
import { Geist, Spectral, Spectral_SC } from "next/font/google";
import "./globals.scss";
import localFont from "next/font/local";
import { CSSProperties } from "react";
import Header from "./components/header/Header";

const spectral = Spectral({
  variable: "--fontS",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const spectralSC = Spectral_SC({
  variable: "--fontSC",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const starlight = localFont({
  src: [
    {
      path: "./fonts/starlightrune.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Opaliora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spectralSC.variable} ${spectral.variable}`}
        style={
          {
            "--fontSC": spectralSC.style.fontFamily,
            "--fontS": spectral.style.fontFamily,
            "--fontSR": starlight.style.fontFamily,
          } as CSSProperties
        }
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
